spring.application.name=rag-backend

# ======================================================================
# PostgreSQL
# ======================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=raguser
spring.datasource.password=ragpwd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# =======================================================================
# Spring AI OpenAI Configuration - LOCAL EMBEDDING MODEL
# =======================================================================
spring.ai.openai.embedding.base-url=http://127.0.0.1:1234/v1
spring.ai.openai.embedding.api-key=lm-studio
spring.ai.openai.embedding.model=text-embedding-nomic-embed-text-v2-moe
spring.ai.openai.embedding.dimensions=768

# Spring AI OpenAI Configuration for ONLINE CHAT MODEL
#spring.ai.openai.chat.base-url=
# OpenAI
#spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.model=

# ==================================================================
# ONLINE CHAT MODEL - OpenAI
# ==================================================================
#spring.ai.model.chat=openai
#spring.ai.openai.chat.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.model=gpt-5-mini

# ONLINE CHAT MODEL - OpenAI GPT OSS - NVIDIA
#spring.ai.openai.chat.base-url=https://integrate.api.nvidia.com/v1
#spring.ai.openai.chat.api-key=${NVIDIA_API_KEY}
#spring.ai.openai.chat.model=openai/gpt-oss-20b

# ONLINE CHAT MODEL - OpenAI GPT OSS - Groq
spring.ai.openai.chat.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.api-key=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
spring.ai.openai.chat.model=openai/gpt-oss-20b

# Contrôle le niveau de créativité et de variabilité des réponses du modèle.
# Une valeur faible produit des réponses plus stables, factuelles et prévisibles.
# Une valeur élevée produit des réponses plus variées et plus créatives.
# Pour un assistant technique Orange basé sur un RAG, 0.2 est recommandé
# afin de limiter les hallucinations et de rester fidèle à la documentation récupérée.
spring.ai.openai.chat.temperature=0.2
# ==================================================================
# PgVector
# ==================================================================
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768

# ==================================================================
# Orange Assistance Documentation
# ==================================================================
orange.assistance.allowed-hosts=www.orange.fr,assistance.orange.fr
orange.assistance.timeout=15000
orange.assistance.user-agent=Mozilla/5.0

# ==================================================================
# RAG - Vector Search
# ==================================================================

# Nombre maximum de chunks/documentations récupérés depuis PgVector
# pour une question utilisateur.
# Plus la valeur est élevée, plus le contexte envoyé au LLM sera grand.
# 3 est un bon point de départ pour limiter le bruit et la latence.
rag.search.top-k=4

# Seuil minimum de similarité pour accepter un résultat vectoriel.
# Valeur comprise entre 0 et 1.
# Exemple : 0.65 signifie que les chunks avec une similarité inférieure
# à 65% seront ignorés.
# Plus le seuil est élevé, plus la recherche est stricte.
rag.search.similarity-threshold=0.0

# ==================================================================
# RAG - Document Splitting
# ==================================================================

# Taille cible maximale d'un chunk en tokens.
# Le splitter essaie de découper chaque document autour de cette taille.
# 400 permet de rester sous la limite de 512 tokens de ton modèle d'embedding.
rag.splitter.chunk-size=400

# Taille minimale en caractères avant d'accepter une coupure naturelle
# dans le texte.
# Cela évite de créer trop rapidement des petits chunks.
rag.splitter.min-chunk-size-chars=100

# Taille minimale d'un chunk pour qu'il soit conservé et envoyé
# au modèle d'embedding.
# Les morceaux trop courts ou peu utiles peuvent ainsi être ignorés.
rag.splitter.min-chunk-length-to-embed=5

# Nombre maximum de chunks pouvant être générés à partir d'un seul document.
# Cette limite sert principalement de protection contre les documents
# anormalement volumineux ou une mauvaise extraction HTML.
rag.splitter.max-num-chunks=10000

# Indique si les séparateurs du texte doivent être conservés
# lors du découpage : retours à la ligne, séparations de paragraphes, etc.
# true permet de mieux préserver la structure du tutoriel.
rag.splitter.keep-separator=true