services:

  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: rag-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d:ro

    networks:
      - rag-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    security_opt:
      - no-new-privileges:true

  pgadmin:
    image: dpage/pgadmin4:9.17
    container_name: rag-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_DISABLE_POSTFIX: "1"
      PGADMIN_LISTEN_PORT: "8080"

    ports:
      - "127.0.0.1:5050:8080"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    networks:
      - rag-network

    depends_on:
      postgres:
        condition: service_healthy

    security_opt:
      - no-new-privileges:true


networks:
  rag-network:
    driver: bridge


volumes:
  postgres_data:
  pgadmin_data: